### PR TITLE
Corrected bug for the labels

### LINKED ISSUE #31: Sesheta merged with ```do-not-merge/work-in-progress label```
**Describe the bug**
Sesheta merged with ```do-not-merge/work-in-progress label```

**Expected behavior**
PR not merged due to the label.

**Additional context**
Example: https://github.com/thoth-station/graph-sync-job/pull/233

### PR DESCRIPTION
**Pull request by pacospace**
PR Fixes: https://github.com/AICoE/sesheta/issues/31 

Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

### CODE REVIEW

**Review by fridex — APPROVED** [review]
Cool thanks!

**Comment by harshad16** [comment]
Thanks for the fix, @pacospace.
But the thing is we no longer use approver.py :sweat_smile: 
Last time when we encountered this is, we were going to incorporate in the sesheta code, later decided zuul ci should take care of this thing.
Reference: https://github.com/AICoE/sesheta/issues/23

**Review by harshad16 — APPROVED** [review]
:100:

**Comment by pacospace** [comment]
Thanks @harshad16 :smiley: at least we learned about the problem :laughing:

**Pull request merged**
