### PR TITLE
Not notifying in chat on doc update pull requests

### PR DESCRIPTION
**Pull request by goern**
Depends-On: https://github.com/thoth-station/zuul-config/pull/52

Signed-off-by: Christoph Görn <goern@redhat.com>

### CODE REVIEW

**Comment by goern** [comment]
recheck

**Comment by harshad16** [comment]
@goern Is it not good that we know our docs are updating, also its just a reminder !?

**Review by harshad16 — APPROVED** [review]
:arrow_up:

**Comment by goern** [comment]
hmm, ja it would be good to know that a routine updated failed. but in general, I don't want a notification if everything is ok, just like unix commands ;)

**Pull request merged**
